### ISSUE TITLE
UI component for change currency/amount/date

### ISSUE THREAD

**Issue by zaharchenko-evgeny** [cuba-platform/currency-addon#1]
If field implements `CurrencyValue` interface then UI field should allow a user to change currency.

UI Field should be defined as
```
<field>
    <currencyAddonField property='<>' datasource='<>'/>
</field>
```

**Comment by maksim-leshukov** [comment]
UI field should consist from:
- text field for amount
- popup button

Popup button should provide ability:
- to see amount in other currencies
- to change amount and currency
- to change date
