### ISSUE TITLE
Override platform Currency UI field  by addon field

### ISSUE THREAD

**Issue by zaharchenko-evgeny** [cuba-platform/currency-addon#3]
`Currency UI field` (currency addon) should be used by default in fieldgroup for `@CurrencyValue` (platform annotation) annotated fields or for fields which have implemented `CurrencyValue` (currency addon) interface.

**Comment by maksim-leshukov** [comment]
Platfrom doesn't support customization of UI field customization.
It's hardcodded in class `com.haulmont.cuba.web.gui.WebComponentsFactory`

We can override implementation class for `CurrencyField` by reflection.

```
Field classesField = WebComponentsFactory.class.getDeclaredField("classes");
classesField.setAccessible(true);

Map<String, Class> className2classMap = (Map<String, Class>) classesField.get(null);
className2classMap.put(CurrencyField.NAME, WebCurrencyAddonField.class);
```

**Comment by maksim-leshukov** [comment]
@zaharchenko-evgeny need to choose solution for customization:

- Improve platform - support field implementation customization
- Define specific field in UI xml (add documentation part) like 
```
<field>
<currencyAddonField .../>
</field>
```
- Use hack via java reflection API
