### ISSUE TITLE
Create new "CurrencyDate" annotation 

### ISSUE THREAD

**Issue by zaharchenko-evgeny** [cuba-platform/currency-addon#4]
in annotation value, there should be a field name which will be used to check currency date

**Comment by maksim-leshukov** [comment]
```
Date doneTimestamp;

@CurrencyDate("doneTimestamp")
@CurrencyValue("USD")
BigDecimal amount;
```

When amount should be converted to other currencies, it will be converted by rate actual on date specified in `doneTimestamp` field.
